# Generated by Django 5.0.2 on 2024-11-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('language', models.CharField(max_length=50)),
                ('analysis_type', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=20)),
                ('line_number', models.IntegerField()),
                ('message', models.TextField()),
                ('suggestion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Code Analyses',
            },
        ),
        migrations.CreateModel(
            name='CodeMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('language', models.CharField(max_length=50)),
                ('lines_of_code', models.IntegerField()),
                ('cyclomatic_complexity', models.IntegerField()),
                ('maintainability_index', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Code Metrics',
            },
        ),
    ]
