AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECR repositories for ThunderCode application'

Resources:
  FrontendRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: thundercode-frontend
      ImageScanningConfiguration:
        ScanOnPush: true
      ImageTagMutability: MUTABLE
      EncryptionConfiguration:
        EncryptionType: AES256

  BackendRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: thundercode-backend
      ImageScanningConfiguration:
        ScanOnPush: true
      ImageTagMutability: MUTABLE
      EncryptionConfiguration:
        EncryptionType: AES256

Outputs:
  FrontendRepositoryURI:
    Description: URI of the Frontend Repository
    Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${FrontendRepository}
    Export:
      Name: !Sub ${AWS::StackName}-FrontendRepositoryURI

  BackendRepositoryURI:
    Description: URI of the Backend Repository
    Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${BackendRepository}
    Export:
      Name: !Sub ${AWS::StackName}-BackendRepositoryURI
